#!/bin/sh
# Script by TD
# Remove XtremeMusic

rm -rf /system/priv-app/Material_Dark_V4A
rm -rf /system/priv-app/MaterialDarkV4A
rm -f /system/priv-app/Material_Dark_V4A.apk
rm -rf /system/app/DolbyMobileAudioEffectService
rm -f /system/app/DolbyMobileAudioEffectService.apk
rm -rf /system/app/XMN
rm -f /system/app/XMN.apk
# rm -f /system/priv-app/SoundAlive_31.apk
rm -rf /system/etc/audio
rm -rf /system/etc/soundimage
rm -rf /system/addon.d
rm -rf /system/dolby
rm -rf /system/data/srs_processing.cfg
rm -rf /system/usr/alsa
rm -rf /system/etc/sforce
rm -rf /system/etc/sony_effect
rm -rf /system/etc/surround_sound
rm -rf /system/etc/waves
rm -rf /system/etc/tfa
rm -rf /system/etc/tfa98xx
# ui_print("|            Deleting apps           |
# ui_print("|                                    |
rm -f /system/app/As.apk
rm -f /system/app/XTREMEMusic.apk
rm -rf /system/app/As
rm -rf /system/priv-app/As
rm -rf /system/app/XTREMEMusic
rm -rf /system/priv-app/XTREMEMusic
rm -rf /system/priv-app/AudioEffects
rm -rf /system/priv-app/DolbyMobileAudioEffectService
rm -f /system/app/AsUI.apk
rm -rf /system/app/AsUI
rm -rf /system/priv-app/AsUI
rm -rf /system/app/MaxxAudio
rm -f /system/app/Pon-3.apk
rm -rf /system/app/Pon-3
rm -f /system/app/AudioEffectService.apk
rm -rf /system/app/AudioEffectService
rm -f /system/app/Pon-3cPanel.apk
rm -rf /system/app/Pon-3cPanel
# ui_print("|          Deleting bin files        |
# ui_print("|                                    |
rm -f /system/etc/permissions/com.huawei.dolby.xml
rm -f /system/etc/permissions/b1.xml
rm -f /system/etc/permissions/com.google.android.media.effects.xml
rm -f /system/etc/permissions/com.sonyericsson.audioeffectif.xml
rm -f /system/etc/permissions/com.sonyericsson.audioeffect.xml
rm -f /system/etc/permissions/com.srs.fusion.fx.xml
rm -f /system/etc/permissions/com.htc.fusion.fx.xml
rm -f /system/bin/basimage_ibeats.bin
rm -f /system/bin/alsa
rm -f /system/bin/alsa_mixer
rm -f /system/bin/alsa_aplay
rm -f /system/bin/alsa_ctl
rm -f /system/bin/arm-linux-gnueabi-sndfile-resample
rm -f /system/bin/asound
rm -f /system/bin/awesome
rm -f /system/bin/mm-audio-alsa-test
rm -f /system/bin/pnpmgr
rm -f /system/bin/clearphase_sp_param
rm -f /system/bin/coef_sforce_music
rm -f /system/bin/coef_sforce_video
rm -f /system/bin/dsx_param_file
rm -f /system/bin/param_sforce_arm
rm -f /system/bin/param_sforce_qdsp
rm -f /system/bin/param_xloud_qdsp
rm -f /system/bin/param_xloud_arm
rm -f /system/bin/image_beatbox_bt.bin
rm -f /system/bin/image_beats_speaker.bin
rm -f /system/bin/image_beats_wireless_bt.bin
rm -f /system/bin/image_gec.bin
rm -f /system/bin/image_gec_2vol.bin
rm -f /system/bin/image_gec_bt.bin
rm -f /system/bin/image_htc_earbud.bin
rm -f /system/bin/image_htc_earbud_2vol.bin
rm -f /system/bin/image_htc_midtier.bin
rm -f /system/bin/image_htc_midtier_2vol.bin
rm -f /system/bin/image_ibeats.bin
rm -f /system/bin/image_ibeats_2vol.bin
rm -f /system/bin/image_ibeats_solo.bin
rm -f /system/bin/image_ibeats_solo_2vol.bin
rm -f /system/bin/image_ibeats_solo_v2.bin
rm -f /system/bin/image_ibeats_solo_v2_2vol.bin
rm -f /system/bin/image_ibeats_v2.bin
rm -f /system/bin/image_ibeats_v2_2vol.bin
rm -f /system/bin/snd
rm -f /system/bin/snd8k
rm -f /system/bin/snd3254
rm -f /system/bin/sound
rm -f /system/bin/basimage_ibeats_pro.bin
rm -f /system/bin/basimage_ibeats_solo.bin
rm -f /system/bin/basimage_ibeats_solo_x.bin
rm -f /system/bin/basimage_ibeats_studio.bin
rm -f /system/bin/basimage_ibeats_x.bin
rm -f /system/bin/dynimage_gec.bin
rm -f /system/bin/dynimage_gec_bt.bin
rm -f /system/bin/dynimage_ibeats.bin
rm -f /system/bin/dynimage_ibeats_solo.bin
rm -f /system/bin/dynimage_ibeats_solo_x.bin
rm -f /system/bin/dynimage_ibeats_pro.bin
rm -f /system/bin/dynimage_ibeats_studio.bin
rm -f /system/bin/dynimage_ibeats_x.bin
rm -f /system/bin/peqimage_gec.bin
rm -f /system/bin/peqimage_gec_bt.bin
rm -f /system/bin/peqimage_ibeats.bin
rm -f /system/bin/peqimage_ibeats_pro.bin
rm -f /system/bin/peqimage_ibeats_solo.bin
rm -f /system/bin/peqimage_ibeats_solo_x.bin
rm -f /system/bin/peqimage_ibeats_studio.bin
rm -f /system/bin/peqimage_ibeats_x.bin
rm -f /system/bin/beatsbass
rm -f /system/bin/beatsnormal
rm -f /system/bin/sound
rm -f /system/bin/sound8064
rm -f /system/bin/sound8960
rm -f /system/bin/sound8x60
rm -f /system/bin/spkamp
# ui_print("|         Deleting etc files         |
# ui_print("|                                    |
rm -f /system/etc/aeqcoe.txt
rm -f /system/etc/AudioFilter.csv
rm -f /system/vendor/etc/diracmobile.config
rm -f /system/etc/AdieHWCodec_BEATS_HW.csv
rm -f /system/etc/AIC3008_REG_DualMic.csv
rm -f /system/etc/AIC3008_REG_DualMic_XC.csv
rm -f /system/etc/AIC3254_REG.csv
rm -f /system/etc/AIC3254_REG_DualMic.csv
rm -f /system/etc/AIC3254_REG_XD.csv
rm -f /system/etc/AudioBTID.csv
rm -f /system/etc/Beats.db
rm -f /system/etc/AudioFilter_HP.csv
rm -f /system/etc/AudioFilterPlatform.csv
rm -f /system/etc/AudioFilterProduct.csv
rm -f /system/etc/AudioPara_HTC_NEL.csv
rm -f /system/etc/AudioPara4.csv
rm -f /system/etc/AudioPara4_WB.csv
rm -f /system/etc/AudioPreProcess.csv
rm -f /system/etc/AutoVolumeControl.txt
rm -f /system/etc/AudioPara4.csv
rm -f /system/etc/basimage_gec.bin
rm -f /system/etc/basimage_gec_bt.bin
rm -f /system/etc/basimage_ibeats.bin
rm -f /system/etc/basimage_ibeats_pro.bin
rm -f /system/etc/basimage_ibeats_solo.bin
rm -f /system/etc/basimage_ibeats_studio.bin
rm -f /system/etc/dynimage_gec.bin
rm -f /system/etc/dynimage_gec_bt.bin
rm -f /system/etc/dynimage_ibeats.bin
rm -f /system/etc/dynimage_ibeats_solo.bin
rm -f /system/etc/dynimage_ibeats_pro.bin
rm -f /system/etc/dynimage_ibeats_studio.bin
rm -f /system/etc/peqimage_gec.bin
rm -f /system/etc/peqimage_gec_bt.bin
rm -f /system/etc/peqimage_ibeats.bin
rm -f /system/etc/peqimage_ibeats_solo.bin
rm -f /system/etc/peqimage_ibeats_pro.bin
rm -f /system/etc/eqfilter.txt
rm -f /system/etc/HP_Audio.csv
rm -f /system/etc/HP_Video.csv
rm -f /system/etc/pvplayer.cfg
rm -f /system/etc/lmfilter.txt
rm -f /system/etc/situation.txt
rm -f /system/etc/soundbooster.txt
rm -f /system/etc/stream_earpiece.txt
rm -f /system/etc/stream_headset.txt
rm -f /system/etc/stream_speaker.txt
rm -f /system/etc/CodecDSPID.csv
rm -f /system/etc/CodecDSPID_NEL.csv
rm -f /system/etc/CodecDSPID_WB.csv
rm -f /system/etc/CodecDSPID_XA.csv
rm -f /system/etc/DSP_number.txt
rm -f /system/etc/image_beatbox_bt.bin
rm -f /system/etc/image_beats_speaker.bin
rm -f /system/etc/image_beats_wireless_bt.bin
rm -f /system/etc/image_gec_2vol.bin
rm -f /system/etc/image_htc_earbud.bin
rm -f /system/etc/image_htc_earbud_2vol.bin
rm -f /system/etc/image_htc_midtier.bin
rm -f /system/etc/image_htc_midtier_2vol.bin
rm -f /system/etc/image_ibeats_2vol.bin
rm -f /system/etc/image_ibeats_solo_2vol.bin
rm -f /system/etc/image_ibeats_solo_v2.bin
rm -f /system/etc/image_ibeats_solo_v2_2vol.bin
rm -f /system/etc/image_ibeats_v2.bin
rm -f /system/etc/image_ibeats_v2_2vol.bin
rm -f /system/etc/pvplayer.cfg
rm -f /system/etc/sound_mfg.txt
rm -f /system/etc/SRSAudioFilter.csv
rm -f /system/etc/TPA2051_CFG.csv
rm -f /system/etc/TPA2051_CFG_BEATS_HW
rm -f /system/etc/dsx_param_file.bin
rm -f /system/etc/sound_mfg_DMIC.csv
rm -f /system/etc/TPA2051_CFG_XC.csv
# show_progress(0.5, 4);
# ui_print("|    Deleting frameworks files  |
rm -f /system/framework/b1.jar
rm -f /system/framework/dolby.jar
rm -f /system/framework/com.sonyericsson.audioeffect.jar
rm -f /system/framework/com.google.android.media.effects.jar
rm -f /system/framework/com.htc.fusion.fx.jar
rm -f /system/framework/com.srs.fusion.fx.jar
rm -f /system/framework/semc_audioeffectif.jar
# ui_print("|            Deleting libs           |
# ui_print("|                                    |
rm -f /system/lib/libswiqibmpcnv.so
rm -f /system/lib/libstagefright_soft_ddpdec.so
rm -f /system/lib/libswiqisettinghelper.so
rm -f /system/lib/soundfx/libbeatsbass.so
rm -f /system/lib/soundfx/libsrsfx.so
rm -f /system/lib/soundfx/libvisualizer.so
rm -f /system/lib/soundfx/libdseffect.so
rm -f /system/lib/soundfx/libcyanogen-dsp.so
rm -f /system/lib/soundfx/libdirac.so
rm -f /system/lib/soundfx/libclearaudiowrapper.so
rm -f /system/lib/soundfx/libdolbymobileeffect.so
rm -f /system/lib/soundfx/libharmancorehtc.so
rm -f /system/lib/soundfx/libldnhncr.so
rm -f /system/lib/soundfx/libposteffectwrapper.so
rm -f /system/lib/soundfx/libsoundaurawrapper.so
rm -f /system/lib/soundfx/libsrscore.so
rm -f /system/lib/soundfx/libsrsfx.so
rm -f /system/lib/soundfx/libdownmix.so
rm -f /system/lib/soundfx/libfnrwrapper.so
rm -f /system/lib/soundfx/libeffectproxy.so
rm -f /system/lib/soundfx/libharmancorehtc.so
rm -f /system/lib/soundfx/libhearingprotection.so
rm -f /system/lib/soundfx/libmixclearaudio+.so
rm -f /system/lib/soundfx/libloudnesswrapper.so
rm -f /system/lib/soundfx/libposteffectwrapper.so
rm -f /system/lib/soundfx/libqcbassboost.so
rm -f /system/lib/soundfx/libqcomvisualizer.so
rm -f /system/lib/soundfx/libqcomvoiceprocessing.so
rm -f /system/lib/soundfx/libqcreverb.so
rm -f /system/lib/soundfx/libqcvirt.so
rm -f /system/lib/soundfx/libsonypostprocbundle.so
rm -f /system/lib/soundfx/libsweffectwrapper.so
rm -f /system/lib/soundfx/libvpt51wrapper.so
rm -f /system/lib/soundfx/libvptwrapper.so
rm -f /system/lib/soundfx/libpon3fx.so
rm -f /system/lib/soundfx/libpon3ponyfx.so
rm -f /system/lib/libacdbmapper.so
rm -f /system/lib/libaudcal.so
rm -f /system/lib/libaudioeq.so
rm -f /system/lib/libaudio-resampler.so
rm -f /system/lib/libasound.so
rm -f /system/lib/libaudio_init.so
rm -f /system/lib/libAudioTrimmer.so
rm -f /system/lib/libbeatscorehtc.so
rm -f /system/lib/libDolby-dsp.so
rm -f /system/lib/libdtsprocessing.so
rm -f /system/lib/libEffectOmxCore.so
rm -f /system/lib/libharmancorehtc.so
rm -f /system/lib/libHHS_ARM.so
rm -f /system/lib/libhtc_acoustic.so
rm -f /system/lib/libmm-audio-resampler.so
rm -f /system/lib/libresample.so
rm -f /system/lib/librawaudiorenderer.so
rm -f /system/lib/libSD_ARM.so
rm -f /system/lib/libsndfile.so
rm -f /system/lib/libsonydseehxwrapper.so
rm -f /system/lib/libsoundhoundaudio.so
rm -f /system/lib/libsrscorehtc.so
rm -f /system/lib/libsrsprocessing.so
rm -f /system/lib/libstagefright_soft_alacdec.so
rm -f /system/lib/libsurround_proc.so
rm -f /system/lib/libvoAudioFR.so
rm -f /system/lib/libvpt51wrapper.so
rm -f /system/lib/libwebrtc_audio_preprocessing.so
rm -f /system/lib/surround_sound_headers.so
rm -f /system/lib/libaudioeq.so
rm -f /system/lib/libbeatsbass.so
rm -f /system/lib/libbeatcorehtc.so
rm -f /system/lib/libbundlewrapper.so
rm -f /system/lib/libdtsprocessing.so
rm -f /system/lib/libDolby-dsp.so
rm -f /system/lib/libharmancorehtc.so
rm -f /system/lib/libSR_AudioIn.so
rm -f /system/lib/libSD_ARM.so
rm -f /system/lib/libSR_AudioIn.so
rm -f /system/lib/libHHS_ARM.so
rm -f /system/lib/libsrsfx.so
rm -f /system/lib/libscorehtc.so
rm -f /system/lib/libsrprocessing.so
rm -f /system/lib/libsrsprocessing.so
rm -f /system/lib/libvoAudioFR.so
rm -f /system/lib/libwebrtc_audio_processing.so
rm -f /system/lib/libDolby-dsp.so
rm -f /system/lib/libEQGraphLib.so
rm -f /system/lib/libMA3-processcode-Coretex_A9.so
rm -f /system/lib/libMA3-wavesfx-Coretex_A9.so
rm -f /system/lib/libosl-maxxaudio-itf.so
rm -f /system/xbin/alsa_amixer
rm -f /system/bin/alsa_amixer
rm -f /system/xbin/alsa_aplay
rm -f /system/xbin/alsa_ctl